apiVersion: apps/v1
kind: Deployment
metadata:
  name: testvid
  namespace: default
spec:
  selector:
    matchLabels:
      app: testvid
  template:
    metadata:
      labels:
        app: testvid
    spec:
      containers:
      - name: testvid
        image: gcr.io/third-project-399423/generatevid:latest
        ports:
        - name: http
          containerPort: 80
      tolerations:
      - key: instance_type
        value: general
        effect: NoSchedule
        operator: Equal
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80